[package]
name = "simplevenom"
version = "2.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
ratatui = "0.29.0"
localize = { git = "https://github.com/PokeJofeJr4th/rust-localize", version = "0.1.0" }
crossterm = "0.28.1"
